/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package savappli;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author khaoula
 */
public class JFrameRechercheAppareil extends javax.swing.JFrame {
    Statement stm;
    ResultSet rs;
    DefaultTableModel dt;
    connexion maConnexion=new connexion();

    /**
     * Creates new form JFrameProductivitéPersonnelle
     */
    /* void Remplir_TableProd(){
          try{
             // dt.setRowCount(0);
              String sql="select N_Serie,Date_E,N_Dossier, from facture where N_Facture_V NOT IN (select N_Facture_V from facture where Date_Facture='0000-00-00')";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
    }*/
         
   void Recherche_Appareil_NumSerie()
   {
   String N_SD=n_sd.getText();
        
        
         
            
              String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as 'Main doeuvre',MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
"from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
"where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
"AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
"AND P.`Id_panne`=A.`Id_panne`\n" +
"AND MO.`Id_MO`=A.`Id_MO`\n" +
"AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
"AND A.N_Serie='"+N_SD+"' ";
              try{
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }  
         n_sd.setText("");
         n_sd.requestFocusInWindow();
  
   }
   
   void Recherche_Appareil_NumDossier()
   {
   String N_SD=n_sd.getText();
        
        try{
             // dt.setRowCount(0);
              String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as 'Main doeuvre',MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
"from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
"where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
"AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
"AND P.`Id_panne`=A.`Id_panne`\n" +
"AND MO.`Id_MO`=A.`Id_MO`\n" +
"AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
"AND A.N_Dossier='"+N_SD+"' ";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
         n_sd.setText("");
         n_sd.requestFocusInWindow();
      
        
   }
    
    public JFrameRechercheAppareil() {
        initComponents();
        //n_sd.requestFocusInWindow();
        n_sd.setFocusTraversalKeysEnabled(false);
        
         //n_serie.setSelected(true);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProd = new javax.swing.JTable();
        n_serie = new javax.swing.JRadioButton();
        n_dossier = new javax.swing.JRadioButton();
        n_sd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recherche Appareil");

        TableProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableProd);

        n_serie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_serie.setText("N° Série  :");
        n_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_serieActionPerformed(evt);
            }
        });

        n_dossier.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_dossier.setText("N° Dossier  :");
        n_dossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_dossierActionPerformed(evt);
            }
        });

        n_sd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_sd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_sdActionPerformed(evt);
            }
        });
        n_sd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n_sdKeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Chercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n_dossier)
                                .addGap(0, 668, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n_serie)
                                .addGap(45, 45, 45)
                                .addComponent(n_sd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(329, 329, 329)))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(n_serie)
                        .addGap(18, 18, 18)
                        .addComponent(n_dossier))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n_sd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(881, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void n_serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_serieActionPerformed
      if(n_serie.isSelected()==true)
      {
        n_sd.requestFocusInWindow();
        n_dossier.setEnabled(false);
      }
      else if(n_serie.isSelected()==false)
      {
        n_dossier.setEnabled(true);
      }
    }//GEN-LAST:event_n_serieActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String N_SD=n_sd.getText();
        if(n_serie.isSelected()==true && n_dossier.isSelected()==false)
        {
        
         try{
             // dt.setRowCount(0);
              String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as 'Main doeuvre',MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
"from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
"where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
"AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
"AND P.`Id_panne`=A.`Id_panne`\n" +
"AND MO.`Id_MO`=A.`Id_MO`\n" +
"AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
"AND A.N_Serie='"+N_SD+"' ";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }  
         n_sd.setText("");
         
        }
        else if(n_dossier.isSelected()==true && n_serie.isSelected()==false)
        {
        try{
             // dt.setRowCount(0);
              String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as 'Main doeuvre',MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
"from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
"where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
"AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
"AND P.`Id_panne`=A.`Id_panne`\n" +
"AND MO.`Id_MO`=A.`Id_MO`\n" +
"AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
"AND A.N_Dossier='"+N_SD+"' ";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
         n_sd.setText("");
      
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void n_dossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_dossierActionPerformed
       if(n_dossier.isSelected()==true)
      {
          n_sd.requestFocusInWindow();
        n_serie.setEnabled(false);
      }
      else if(n_dossier.isSelected()==false)
      {
        n_serie.setEnabled(true);
      }
       
    }//GEN-LAST:event_n_dossierActionPerformed

    private void n_sdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_sdActionPerformed
       
    }//GEN-LAST:event_n_sdActionPerformed

    private void n_sdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_sdKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_TAB)
        {
            if(n_serie.isSelected()==true && n_dossier.isSelected()==false)
        { 
          Recherche_Appareil_NumSerie();
        } else if(n_dossier.isSelected()==true && n_serie.isSelected()==false)
        {
        Recherche_Appareil_NumDossier();
        }
        }
    }//GEN-LAST:event_n_sdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRechercheAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRechercheAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRechercheAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRechercheAppareil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRechercheAppareil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton n_dossier;
    private javax.swing.JTextField n_sd;
    private javax.swing.JRadioButton n_serie;
    // End of variables declaration//GEN-END:variables
}
