/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package savappli;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author khaoula
 */
public class JFrameMiseAJour extends javax.swing.JFrame {
    Statement stm;
    ResultSet rs;
    DefaultTableModel dt;
    connexion maConnexion=new connexion();
    private ResultSet rs1;
    private String add3;
    private String t1;
    private String t;

    /**
     * Creates new form JFrameProductivitéPersonnelle
     */
    /* void Remplir_TableProd(){
          try{
             // dt.setRowCount(0);
              String sql="select N_Serie,Date_E,N_Dossier, from facture where N_Facture_V NOT IN (select N_Facture_V from facture where Date_Facture='0000-00-00')";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
    }*/
     
    void Recherche_Appareil()
    {
          String N_SD=n_sd.getText();
        if(n_serie.isSelected()==true && n_dossier.isSelected()==false)
        {
        
         try{
             // dt.setRowCount(0);
              String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.N_BL,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as Main_Oeuvre,MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
"from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
"where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
"AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
"AND P.`Id_panne`=A.`Id_panne`\n" +
"AND MO.`Id_MO`=A.`Id_MO`\n" +
"AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
"AND A.N_Serie='"+N_SD+"' " +
"ORDER BY `Date_E` DESC "                      ;
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }  
         
         n_serie.setSelected(true);
         
         n_dossier.setEnabled(false);
         n_sd.setText("");
        }
        else if(n_dossier.isSelected()==true && n_serie.isSelected()==false)
        {
        try{
             // dt.setRowCount(0);
              String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.N_BL,A.N_BL,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as Main_Oeuvre,MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
"from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
"where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
"AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
"AND P.`Id_panne`=A.`Id_panne`\n" +
"AND MO.`Id_MO`=A.`Id_MO`\n" +
"AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
"AND A.N_Dossier='"+N_SD+"' ";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableProd.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
         
         n_dossier.setSelected(true);
        // 
         n_serie.setEnabled(false);
         n_sd.setText("");
        }
        n_sd.requestFocusInWindow();
    }
    
    public JFrameMiseAJour() {
        initComponents();
        n_sd.setFocusTraversalKeysEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProd = new javax.swing.JTable();
        n_serie = new javax.swing.JRadioButton();
        n_dossier = new javax.swing.JRadioButton();
        n_sd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        n_serie1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        n_dossier1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_e = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        type_app = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panne = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modification des Erreurs de Saisie");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        TableProd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProd);

        n_serie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_serie.setText("N° Série  :");
        n_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_serieActionPerformed(evt);
            }
        });

        n_dossier.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_dossier.setText("N° Dossier  :");
        n_dossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_dossierActionPerformed(evt);
            }
        });

        n_sd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_sd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n_sdKeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Chercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("N° de série :");

        n_serie1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_serie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_serie1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("N° dossier :");

        n_dossier1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        n_dossier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_dossier1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Type d'appareil :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Date d'entrée :");

        date_e.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        date_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_eActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Description :");

        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        desc.setLineWrap(true);
        desc.setRows(5);
        desc.setWrapStyleWord(true);
        desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(desc);

        type_app.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Panne :");

        panne.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_serie)
                            .addComponent(n_dossier))
                        .addGap(18, 18, 18)
                        .addComponent(n_sd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date_e, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(n_dossier1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n_serie1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(type_app, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panne, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(n_serie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n_dossier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n_sd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(n_serie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_app, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(panne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_dossier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1052, 615));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String N_S = n_serie1.getText();
        //String D_BL = date_bl.getText();
        String N_D = n_dossier1.getText();
        String D_E = date_e.getText();
        String T_A = type_app.getText();
        String DES = desc.getText();
        //String E = etat.getText();
        String P = panne.getText();
        //String N_D = n_dossier1.getText();

        //la requête
        String requete1= "UPDATE appareil SET N_Serie='"+N_S+"',N_Dossier='"+N_D+"',Date_E='"+D_E+"',Type_App='"+T_A+"',Description='"+DES+"',Id_panne=(select Id_panne from panne where type='"+P+"') WHERE (N_Serie='"+t+"' AND N_BL IN(1,2,3) AND Date_E='"+t1+"')";

        //Exécuter la requête
        try{
            stm=maConnexion.get_connexion().createStatement();
            // stm.executeQuery(requete); ne passe pas pour l'insertion dans mysql

            stm.executeUpdate(requete1);
            //  stm.executeUpdate(requete2);
            JOptionPane.showMessageDialog(null,"les modifications sont prises en compte");
            n_serie1.setText("");
            n_dossier1.setText("");
            date_e.setText("");
            type_app.setText("");
            desc.setText("");
            // etat.setText("");
            panne.setText("");
            //etat.setText("");
            //((JTextField)date_blv.getDateEditor().getUiComponent()).setText("");
            n_sd.setText("");

            /*  n_serie.setEnabled(true);
            n_serie.setSelected(true);
            n_dossier.setSelected(false);
            n_dossier.setEnabled(false);*/

        }
        catch(SQLException e){
            System.err.println(e);

        }
        if(n_serie.isSelected()==true)
        {
            n_sd.requestFocusInWindow();

        }else if(n_dossier.isSelected()==true)
        {
            n_sd.requestFocusInWindow();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void descKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descKeyPressed
        desc.setText(desc.getText().replaceAll("\t", System.lineSeparator()));
    }//GEN-LAST:event_descKeyPressed

    private void date_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_eActionPerformed

    private void n_dossier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_dossier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_dossier1ActionPerformed

    private void n_serie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_serie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_serie1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String N_SD=n_sd.getText();
        if(n_serie.isSelected()==true && n_dossier.isSelected()==false)
        {

            try{
                // dt.setRowCount(0);
                String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.N_BL,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as Main_Oeuvre,MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
                "from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
                "where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
                "AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
                "AND P.`Id_panne`=A.`Id_panne`\n" +
                "AND MO.`Id_MO`=A.`Id_MO`\n" +
                "AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
                "AND A.N_Serie='"+N_SD+"' " +
                "ORDER BY `Date_E` DESC ";
                stm=maConnexion.get_connexion().createStatement();
                rs=stm.executeQuery(sql);
                TableProd.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            n_sd.setText("");
            n_serie.setSelected(false);
            n_dossier.setEnabled(true);
        }
        else if(n_dossier.isSelected()==true && n_serie.isSelected()==false)
        {
            try{
                // dt.setRowCount(0);
                String sql="select A.N_Serie,A.N_Dossier,A.Date_E as Date_Entrée,A.Date_R as Date_Réparation,A.N_BL,A.Type_App ,I.type_In AS Intervention,A.Etat,P.type as Panne,A.Description,MO.Type_MO as Main_Oeuvre,MA.Nom as Façade,MA.Type_Mat as Appareil,MA.Couleur,II.Nom\n" +
                "from appareil A,materiel MA,intervention I,panne P,maindoeuvre MO,intervenant II\n" +
                "where MA.`Id_Materiel`=A.`Id_Materiel`\n" +
                "AND I.`Id_Intervention`=A.`Id_Intervention`\n" +
                "AND P.`Id_panne`=A.`Id_panne`\n" +
                "AND MO.`Id_MO`=A.`Id_MO`\n" +
                "AND II.`Id_Intervenant`=A.`Id_Intervenant`\n" +
                "AND A.N_Dossier='"+N_SD+"' ";
                stm=maConnexion.get_connexion().createStatement();
                rs=stm.executeQuery(sql);
                TableProd.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            n_sd.setText("");
            n_dossier.setSelected(false);
            n_serie.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void n_sdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_sdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_TAB)
        {

            Recherche_Appareil();

        }
    }//GEN-LAST:event_n_sdKeyPressed

    private void n_dossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_dossierActionPerformed
        if(n_dossier.isSelected()==true)
        {
            n_sd.requestFocusInWindow();
            n_serie.setEnabled(false);
        }
        else if(n_dossier.isSelected()==false)
        {
            n_serie.setEnabled(true);
        }

    }//GEN-LAST:event_n_dossierActionPerformed

    private void n_serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_serieActionPerformed
        if(n_serie.isSelected()==true)
        {
            n_sd.requestFocusInWindow();
            n_dossier.setEnabled(false);
        }
        else if(n_serie.isSelected()==false)
        {

            n_dossier.setEnabled(true);
        }
    }//GEN-LAST:event_n_serieActionPerformed

    private void TableProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProdMouseClicked

        String PP=null;
        try{
            int row = TableProd.getSelectedRow();
            t = (TableProd.getModel().getValueAt(row, 0).toString());
            t1 = (TableProd.getModel().getValueAt(row, 2).toString());
            String requete= "select * from appareil where (N_Serie='"+t+"' OR N_Dossier='"+t+"') AND Date_E='"+t1+"'" ;
            stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete); //ne passe pas pour l'insertion dans mysql
            //stm.executeUpdate(requete);
            if(rs.next())
            {
                String add1 =rs.getString("N_Serie");
                n_serie1.setText(add1);
                String add2 =rs.getString("N_Dossier");
                n_dossier1.setText(add2);
                String add3 =rs.getString("Date_E");
                date_e.setText(add3);
                String add4 =rs.getString("Type_App");
                type_app.setText(add4);
                String add5 =rs.getString("Description");
                desc.setText(add5);

                PP =rs.getString("Id_panne");
            }

            // JOptionPane.showMessageDialog(null,"le nouveau Bon de livraison est ajouté");
        }
        catch(SQLException e){
            System.err.println(e);
        }
        try{

            String requete= "SELECT Type from Panne WHERE Id_panne='"+PP+"' ";
            stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(requete);
            rs.first();
            String a =rs.getString("type");
            panne.setText(a);
        }
        catch(SQLException e){
            System.err.println(e);
        }

    }//GEN-LAST:event_TableProdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMiseAJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMiseAJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMiseAJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMiseAJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMiseAJour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProd;
    private javax.swing.JTextField date_e;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton n_dossier;
    private javax.swing.JTextField n_dossier1;
    private javax.swing.JTextField n_sd;
    private javax.swing.JRadioButton n_serie;
    private javax.swing.JTextField n_serie1;
    private javax.swing.JTextField panne;
    private javax.swing.JTextField type_app;
    // End of variables declaration//GEN-END:variables
}
