/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package directionappli;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author khaoula
 */
public class JFrameGestionStockDef_Rem extends javax.swing.JFrame {
    
    Statement stm;
    private PreparedStatement pst;
    ResultSet rs,rs1,rs2,rs3;
    connexion maConnexion= new connexion();

    
    
 
 /*  private void Remplir_ComboNom(){
          try{
              String sql="select distinct(Nom) from materiel  where Nom NOT IN (select Nom from materiel where Id_Materiel='1')";
              stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
               while(rs.next())
                {
                  String name=rs.getString("Nom");
                  ComboNom.addItem(name);
                  }
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
    }*/
   
   
     void Remplir_TableStock(){
          try{
              String sql="select Type_Mat as Type_Appareil,Couleur,\n" +
                      "count(CASE WHEN Etat='Acheté' OR Etat='Remplacé' THEN 1 END) as stock_réel,\n" +
"count(CASE WHEN Etat='Défectueux' THEN 1 END) AS stock_défectueux,\n" +
"count(CASE WHEN Etat='Remplacé' THEN 1 END) AS stock_remplacé,\n" +

"(count(CASE WHEN Etat='Défectueux' THEN 1 END)-count(CASE WHEN Etat='Remplacé' THEN 1 END)) as cmptD_R\n" +
"from materiel\n" +
"where Id_Materiel!='1'\n" +
"GROUP BY Type_Mat,Couleur ORDER BY Type_Mat,Couleur DESC";
             stm=maConnexion.get_connexion().createStatement();
              rs=stm.executeQuery(sql);
              TableStock.setModel(DbUtils.resultSetToTableModel(rs));
               }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
              }
    }
     

    /**
     * Creates new form JFrameGestionStockDef_Rem
     */
    public JFrameGestionStockDef_Rem() {
        initComponents();
        //Remplir_ComboApp();
        //Remplir_ComboCouleur();
       // Remplir_TableStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStock = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reel = new javax.swing.JTextField();
        def = new javax.swing.JTextField();
        remp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Stock \" Acheté / Défectueux  / Remplacé \"");

        TableStock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableStock);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Afficher toute la liste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Valeur du Stock   :");

        reel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        def.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        remp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Valeur Globale du stock :");

        stock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(def, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(151, 151, 151))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(989, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Remplir_TableStock();
       double tau=0,tau1=0,tau2=0,tau3=0,pa_s=0,pa_s1=0,pa_s2=0,pa_s3=0,result_s=0,result_s1=0,result_s2=0,result_s3=0,s_s=0,s_s1=0,s_s2=0,s_s3=0;
       String sql="select Prix_Achat,Taux_Conversion from materiel where Etat!='Utilisé' AND Id_Materiel!='1'";
       String sql1="select Prix_Achat,Taux_Conversion from materiel where Etat IN ('Acheté','Remplacé') AND Id_Materiel!='1'";
       String sql2="select Prix_Achat,Taux_Conversion from materiel where Etat='Défectueux'";
       String sql3="select Prix_Achat,Taux_Conversion from materiel where Etat='Remplacé'";
       //////////////***************VALEUR GLOBAL DU STOCK *********///////////////////
        try{
            stm=maConnexion.get_connexion().createStatement();
            rs=stm.executeQuery(sql); 
            
              for(int i=1;i<100000;i++)
             {
                 if(rs.absolute(i))
                 {
                 tau = rs.getDouble("Taux_Conversion");
                // System.out.println(tva);
                 pa_s = rs.getDouble("Prix_Achat");
                // System.out.println(pa);
                
                  //System.out.println(div);
                 result_s=(double)pa_s/tau;
                 // System.out.println(result);
                  s_s+=result_s;
                 }
            
              }
          System.out.println(s_s);
           String mt_s=String.valueOf(s_s);
           stock.setText(mt_s);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }    
       //////////////////********VALEUR  STOCK REEL  ************//////////////////
        try{
            stm=maConnexion.get_connexion().createStatement();
            rs1=stm.executeQuery(sql1); 
            
              for(int i=1;i<100000;i++)
             {
                 if(rs1.absolute(i))
                 {
                 tau1 = rs1.getDouble("Taux_Conversion");
                // System.out.println(tva);
                 pa_s1 = rs1.getDouble("Prix_Achat");
                // System.out.println(pa);
                
                  //System.out.println(div);
                 result_s1=(double)pa_s1/tau1;
                 // System.out.println(result);
                  s_s1+=result_s1;
                 }
            
              }
          System.out.println(s_s1);
           String mt_s=String.valueOf(s_s1);
           reel.setText(mt_s);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }  
        //////////////////********VALEUR  STOCK DEFECTUEUX  ************//////////////////
        try{
            stm=maConnexion.get_connexion().createStatement();
            rs2=stm.executeQuery(sql2); 
            
              for(int i=1;i<100000;i++)
             {
                 if(rs2.absolute(i))
                 {
                 tau2 = rs2.getDouble("Taux_Conversion");
                // System.out.println(tva);
                 pa_s2 = rs2.getDouble("Prix_Achat");
                // System.out.println(pa);
                
                  //System.out.println(div);
                 result_s2=(double)pa_s2/tau2;
                 // System.out.println(result);
                  s_s2+=result_s2;
                 }
            
              }
          System.out.println(s_s2);
           String mt_s=String.valueOf(s_s2);
           def.setText(mt_s);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }    
       //////////////////********VALEUR  STOCK REMPLACE  ************////////////////// 
        try{
            stm=maConnexion.get_connexion().createStatement();
            rs3=stm.executeQuery(sql3); 
            
              for(int i=1;i<100000;i++)
             {
                 if(rs3.absolute(i))
                 {
                 tau3 = rs3.getDouble("Taux_Conversion");
                // System.out.println(tva);
                 pa_s3 = rs3.getDouble("Prix_Achat");
                // System.out.println(pa);
                
                  //System.out.println(div);
                 result_s3=(double)pa_s3/tau3;
                 // System.out.println(result);
                  s_s3+=result_s3;
                 }
            
              }
          System.out.println(s_s3);
           String mt_s=String.valueOf(s_s3);
           remp.setText(mt_s);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }    
                         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionStockDef_Rem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionStockDef_Rem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionStockDef_Rem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionStockDef_Rem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGestionStockDef_Rem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStock;
    private javax.swing.JTextField def;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reel;
    private javax.swing.JTextField remp;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
