/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package directionappli;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khaoula
 */
public class JFrameEtatBancaire extends javax.swing.JFrame {
    Statement stm;
    ResultSet rs,rs1,rs2,rs3,rs4,rs5,rs6,rs7,rs8;
    DefaultTableModel dt;
    connexion maConnexion=new connexion();

    /**
     * Creates new form JFrameEtatBanquaire
     */
    public JFrameEtatBancaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pos_th = new javax.swing.JTextField();
        pos_ef = new javax.swing.JTextField();
        genere = new javax.swing.JTextField();
        consm = new javax.swing.JTextField();
        marge_b = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tva_verse = new javax.swing.JTextField();
        tva_c = new javax.swing.JTextField();
        tva_r = new javax.swing.JTextField();
        val_stock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Position Théorique :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Position Effective :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Généré :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Consommé :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Marge Brute :");

        pos_th.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pos_th.setText(" ");

        pos_ef.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        genere.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        consm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        marge_b.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        marge_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marge_bActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Calcul");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("TVA Versée :");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("TVA Colléctée");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("TVA :");

        tva_verse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        tva_c.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        tva_r.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        val_stock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Valeur du Stock :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genere, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(val_stock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pos_th)
                    .addComponent(marge_b)
                    .addComponent(consm)
                    .addComponent(tva_c)
                    .addComponent(tva_verse)
                    .addComponent(tva_r)
                    .addComponent(pos_ef))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pos_th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pos_ef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(genere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(consm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(marge_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tva_verse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tva_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tva_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(val_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(646, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void marge_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marge_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marge_bActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String sql=" select sum(Prix_Achat) as Achat from achat";
    String sql1=" select sum(Montant_F) as Vente from facture";
    String sql2="select Prix_Achat , TVA from achat where Etat='payée'";
    String sql3="select Montant_F , TVA_V from facture where Etat_F='payée'";
    String sql4="select Prix_Achat , TVA from achat";
    String sql5="select Montant_F , TVA_V from facture";
    String sql6="select sum(Prix_Achat) as TVA from achat where Type='TVA'";
    String sql7="select Prix_Achat , TVA from achat where Type='Fourniture'";
    String sql8="select Prix_Achat,Taux_Conversion from materiel where Etat!='Utilisé' AND Id_Materiel!='1'";
    double at=0,tv=0,tau=0,pa_s=0;
    double vt=0;
    double s1=0,s11=0,s117=0,s41=0;
    double tva=0,tva1=0,tva17=0;
    double pa=0,pa1=0,pa17=0;
    double result=0,result1=0,result17=0;
    double s2=0,s21=0,s_s=0;
    double tva_v=0,tva_v1=0;
    double pv=0,pv1=0;
    double result_v=0,result_v1=0,result_v4=0,result_s=0;
    //String mt_a;
    //String mt_v;
        //Calcul des Achats sans la TVA dont l'état n'importe
        try{
         stm=maConnexion.get_connexion().createStatement();
         rs=stm.executeQuery(sql);
            if(rs.first())
                {
                at = rs.getDouble("Achat");
                //System.out.println(at);
                }  
            }
        catch(SQLException e){
           System.err.println(e);    
    }
        //Calcul des Ventes sans la TVA dont l'état n'importe
         try{
            stm=maConnexion.get_connexion().createStatement();
            rs1=stm.executeQuery(sql1);  
             if(rs1.first())
                {
               vt = rs1.getDouble("Vente");
              // System.out.println(vt);
                }
             }
        catch(SQLException e){
           System.err.println(e);    
    }
         
                
               String g=String.valueOf(vt);
               genere.setText(g);
               String c=String.valueOf(at);
               consm.setText(c);
               //Calcul de la Marge Brut Généré - Consommé
               double s=0;
               s=vt-at;
    
               String m=String.valueOf(s);
               marge_b.setText(m);
    //Calcul de Position Effective
     
     //Calcul des Achats Inclut la TVA dont l'état est payé     
         try{
            stm=maConnexion.get_connexion().createStatement();
            rs2=stm.executeQuery(sql2); 
            
              for(int i=1;i<1000;i++)
             {
                 if(rs2.absolute(i))
                 {
                 tva = rs2.getDouble("TVA");
                // System.out.println(tva);
                 pa = rs2.getDouble("Prix_Achat");
                // System.out.println(pa);
                 double div=tva/100;
                  //System.out.println(div);
                 result=(double)((tva/100)*pa)+pa;
                 // System.out.println(result);
                  s1+=result;
                 }
            
              }
          System.out.println(s1);
           // mt_a=String.valueOf(s1);
           // pos_ef.setText(mt_a);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }
         
    //Calcul des Ventes Inclut la TVA dont l'état est payé 
    try{
            stm=maConnexion.get_connexion().createStatement();
            rs3=stm.executeQuery(sql3); 
            
              for(int i=1;i<1000;i++)
             {
                 if(rs3.absolute(i))
                 {
                 tva_v = rs3.getDouble("TVA_V");
                // System.out.println(tva_v);
                 pv = rs3.getDouble("Montant_F");
                 //System.out.println(pv);
                 
                 //float div=(float)tva_v/100;
                 
                 //System.out.println(div);
                 result_v=(double)((tva_v/100)*pv)+pv;
                 // System.out.println(result_v);
                  s2+=result_v;
                 }
            
              }
            //System.out.println(s2);
            //mt_v=String.valueOf(s2);
           // pos_ef.setText(mt);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }	
     double mt_res=0;
     mt_res=s2-s1; 
     String mt_rs=String.valueOf(mt_res);
     pos_ef.setText(mt_rs);
     
     //Calcul de Position Théorique
     
     //Calcul des Achats Inclut la TVA dont l'état n'importe
     try{
            stm=maConnexion.get_connexion().createStatement();
            rs4=stm.executeQuery(sql4); 
            
              for(int i=1;i<1000;i++)
             {
                 if(rs4.absolute(i))
                 {
                 tva1 = rs4.getDouble("TVA");
                // System.out.println(tva);
                 pa1 = rs4.getDouble("Prix_Achat");
                // System.out.println(pa);
                 //double div=tva/100;
                  //System.out.println(div);
                 result1=(double)((tva1/100)*pa1)+pa1;
                 // System.out.println(result);
                  s11+=result1;
                 }
            
              }
          //  System.out.println(s1);
           // mt_a=String.valueOf(s1);
           // pos_ef.setText(mt_a);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }
     
     //Calcul des Ventes Inclut la TVA dont l'état n'importe
    try{
            stm=maConnexion.get_connexion().createStatement();
            rs5=stm.executeQuery(sql5); 
            
              for(int i=1;i<1000;i++)
             {
                 if(rs5.absolute(i))
                 {
                 tva_v1 = rs5.getDouble("TVA_V");
                 //System.out.println(tva_v1);
                 pv1 = rs5.getDouble("Montant_F");
                // System.out.println(pv1);
                 
                // float div=(float)tva_v/100;
                 
                // System.out.println(div);
                 result_v1=(double)((tva_v1/100)*pv1)+pv1;
                 result_v4=(double)(tva_v1/100)*pv1;
                System.out.println(result_v4);
                  s21+=result_v1;
                  s41+=result_v4;
                 }
            
              }
           System.out.println(s41);
            String mt_tva_c=String.valueOf(s41);
           tva_c.setText(mt_tva_c);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }	
     double mt_res1=0;
     mt_res1=s21-s11; 
     String mt_rs1=String.valueOf(mt_res1);
     pos_th.setText(mt_rs1);   
     
     //Calcul de la TVA Versé
     //1) TVA des achats Fourniture
     try{
            stm=maConnexion.get_connexion().createStatement();
            rs7=stm.executeQuery(sql7); 
            
              for(int i=1;i<1000;i++)
             {
                 if(rs7.absolute(i))
                 {
                 tva17 = rs7.getDouble("TVA");
                // System.out.println(tva);
                 pa17 = rs7.getDouble("Prix_Achat");
                // System.out.println(pa);
                 //double div=tva/100;
                  //System.out.println(div);
                 result17=(double)((tva17/100)*pa17);
                // System.out.println(result17);
                  s117+=result17;
                 }
            
              }
          // System.out.println(s117);
           // mt_a=String.valueOf(s1);
           // pos_ef.setText(mt_a);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }
     //Calcul des Factures TVA
        try{
         stm=maConnexion.get_connexion().createStatement();
         rs6=stm.executeQuery(sql6);
            if(rs6.first())
                {
                tv = rs6.getDouble("TVA");
                //System.out.println(tv);
                }  
            }
        catch(SQLException e){
           System.err.println(e);    
    }
               double mt_tva=0;
               mt_tva=tv+s117;
    
               String mt_tv=String.valueOf(mt_tva);
               tva_verse.setText(mt_tv);
     
   //Calcul de la tva restante
               
          double ttva_r=0;
          ttva_r=mt_tva-s41;
          String mt_tv_r=String.valueOf(ttva_r);
          tva_r.setText(mt_tv_r);
          
       //Calcul de la valeur du Stock    
         try{
            stm=maConnexion.get_connexion().createStatement();
            rs8=stm.executeQuery(sql8); 
            
              for(int i=1;i<100000;i++)
             {
                 if(rs8.absolute(i))
                 {
                 tau = rs8.getDouble("Taux_Conversion");
                // System.out.println(tva);
                 pa_s = rs8.getDouble("Prix_Achat");
                // System.out.println(pa);
                
                  //System.out.println(div);
                 result_s=(double)pa_s/tau;
                 // System.out.println(result);
                  s_s+=result_s;
                 }
            
              }
          System.out.println(s_s);
           String mt_s=String.valueOf(s_s);
           val_stock.setText(mt_s);
            
             }
        catch(SQLException e){
           System.err.println(e);    
    }    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEtatBancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEtatBancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEtatBancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEtatBancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEtatBancaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField consm;
    private javax.swing.JTextField genere;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marge_b;
    private javax.swing.JTextField pos_ef;
    private javax.swing.JTextField pos_th;
    private javax.swing.JTextField tva_c;
    private javax.swing.JTextField tva_r;
    private javax.swing.JTextField tva_verse;
    private javax.swing.JTextField val_stock;
    // End of variables declaration//GEN-END:variables
}
